import {
  LuCalendar,
  LuCheck,
  LuChevronLeft,
  LuChevronRight,
  LuChevronsUpDown,
  LuCircle,
  LuCircleOff,
  LuLoader2,
  LuMenu,
  LuMoon,
  LuPiggyBank,
  LuPlusSquare,
  LuSearch,
  LuSun,
  LuX,
} from 'react-icons/lu'

export const Icons = {
  piggyBank: LuPiggyBank,
  sun: LuSun,
  moon: LuMoon,
  check: LuCheck,
  circle: LuCircle,
  chevronRight: LuChevronRight,
  chevronLeft: LuChevronLeft,
  chevronsUpDown: LuChevronsUpDown,
  X: LuX,
  menu: LuMenu,
  search: LuSearch,
  plusSquare: LuPlusSquare,
  circleOff: LuCircleOff,
  loading: LuLoader2,
  calendar: LuCalendar,
}
