import {
  LuCalendar,
  LuCheck,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuChevronsUpDown,
  LuChevronUp,
  LuCircle,
  LuCircleOff,
  LuLoader2,
  LuMenu,
  LuMoon,
  LuPiggyBank,
  LuPlusSquare,
  LuSearch,
  LuSun,
  LuTrendingDown,
  LuTrendingUp,
  LuWallet,
  LuX,
} from 'react-icons/lu'

export const Icons = {
  piggyBank: LuPiggyBank,
  sun: LuSun,
  moon: LuMoon,
  check: LuCheck,
  circle: LuCircle,
  chevronRight: LuChevronRight,
  chevronLeft: LuChevronLeft,
  chevronUp: LuChevronUp,
  chevronDown: LuChevronDown,
  chevronsUpDown: LuChevronsUpDown,
  X: LuX,
  menu: LuMenu,
  search: LuSearch,
  plusSquare: LuPlusSquare,
  circleOff: LuCircleOff,
  loading: LuLoader2,
  calendar: LuCalendar,
  trendingDown: LuTrendingDown,
  trendingUp: LuTrendingUp,
  wallet: LuWallet,
}
